### ISSUE TITLE
SetBoardMatrix

### ISSUE THREAD

**Issue by roodyridar2** [aykutkardas/match-3-game-engine#18]
I couldn't find any way to setBoardMatrix

**Comment by aykutkardas** [comment]
I use board Matrix only as a helper to draw the board on the screen. You can use `updateBoard` to update the board.

**Comment by roodyridar2** [comment]
Thank you for your response! You've built an amazing game. I would like to integrate Socket so that the game board state is managed on the backend. For example, I want the backend to handle moving pieces and then send the updated board state to the client, which will then update its view accordingly in client. However, I’m not entirely sure how to implement the board update process. Could you provide some guidance on this?

**Comment by aykutkardas** [comment]
I apologize for the late response. You can store the game board on the server and deliver the updated board after each user action, such as moving an item or changing the turn. We had done this as open source before, but it can be a bit complex

https://github.com/aykutkardas/checkers.place
